### ISSUE TITLE
Removing SCSS deps, and changing the namespace to be similar to addon name

### ISSUE THREAD

**Issue by oriSomething** [eshirazi/ember-resizable-table#4]
- `.resizable-table` -> to `.ember-resizable-table`
- There is not enough CSS to justify forcing installing this dep

**Comment by eshirazi** [comment]
Done! Since there is very little non-dynamic styles on the projects, I changed the styling approach to be inline style based.
Relevant commits:
- https://github.com/eshirazi/ember-resizable-table/commit/f019b4ccd291a9ce032ff0df0802640dab415d6a
- https://github.com/eshirazi/ember-resizable-table/commit/04fa6c3a27f2b5bf8aaedf56ef30e9337b2c1326
